### ISSUE TITLE
Using merged mutation file for regions with low mutation burden

### ISSUE THREAD

**Issue by mortunco** [reimandlab/ActiveDriverWGS#6]
Hi,

I would like use this software slightly different than the example usage. I am working on prostate cancer snv data and we have ~4k TF binding regions. Our mutation burden is pretty low these regions. (~5 mutation/patient). 

Our aim is to tell that within ~4k TF binding regions; 
- Regions that have higher than x mutation should be considered as hyper mutated binding regions.

So instead of specifying patient1-2-3-4-5-6 in the mutation file can I simply give patient1 to all of my mutations? 

Thank you very much for the help and discussion,

Best regards,

Tunc.

**Comment by reimand0** [comment]
Hi Tunc - This won't work as we count only one mutation per patient per region for statistics estimates. please feel free to email me at juri.reimand at utoronto dot ca for more discussion
