### ISSUE TITLE
arguments imply differing number of rows: 0, 1

### ISSUE THREAD

**Issue by Colin-Cheng** [reimandlab/ActiveDriverWGS#7]
I am running the exact sample code in R studio. When I was running the following code:
`# find_drivers
results <- find_drivers(prepare_elements_regions_tf, 
                        "all_mutations_WGS.txt")
`
I got this error:
`Error in data.frame(id, pp_site = NA, pp_element = NA, element_muts_obs = NA,  : 
  arguments imply differing number of rows: 0, 1`

Could anyone give some hint?

**Comment by jknp** [comment]
Dear reimandlab,

I'm experiencing the same issue as the topic starter. I'm using ActiveDriverWGS version 1.0.1.

`results = ActiveDriverWGS(mutations = cll_mutations, elements = ele, sites = bsites)`
gives
`1 remove hypermut, n= 92699 ,  9 %
hypermuted samples:  #name of sample

reversing 0 positions
Removing  1  invalid SNVs

Tests to do:  0 
.Error in data.frame(id, pp_element = NA, element_muts_obs = NA, element_muts_exp = NA,  : 
  arguments imply differing number of rows: 0, 1`

Input arguments satisfy requirements as stated in readme.

Any thoughts on what might be causing this and how to solve it?

**Comment by reimand0** [comment]
have a look at this repository instead - https://github.com/reimandlab/ActiveDriverWGSR. Please let me know in case this did not solve your issue. Will close now. This repository is deprecated and will be removed shortly.
